// This file is generated by rust-protobuf 3.1.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `feast/storage/Redis.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_1_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:feast.storage.RedisKeyV2)
pub struct RedisKeyV2 {
    // message fields
    // @@protoc_insertion_point(field:feast.storage.RedisKeyV2.project)
    pub project: ::std::string::String,
    // @@protoc_insertion_point(field:feast.storage.RedisKeyV2.entity_names)
    pub entity_names: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:feast.storage.RedisKeyV2.entity_values)
    pub entity_values: ::std::vec::Vec<super::Value::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:feast.storage.RedisKeyV2.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RedisKeyV2 {
    fn default() -> &'a RedisKeyV2 {
        <RedisKeyV2 as ::protobuf::Message>::default_instance()
    }
}

impl RedisKeyV2 {
    pub fn new() -> RedisKeyV2 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "project",
            |m: &RedisKeyV2| { &m.project },
            |m: &mut RedisKeyV2| { &mut m.project },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "entity_names",
            |m: &RedisKeyV2| { &m.entity_names },
            |m: &mut RedisKeyV2| { &mut m.entity_names },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "entity_values",
            |m: &RedisKeyV2| { &m.entity_values },
            |m: &mut RedisKeyV2| { &mut m.entity_values },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RedisKeyV2>(
            "RedisKeyV2",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RedisKeyV2 {
    const NAME: &'static str = "RedisKeyV2";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.project = is.read_string()?;
                },
                18 => {
                    self.entity_names.push(is.read_string()?);
                },
                26 => {
                    self.entity_values.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.project.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.project);
        }
        for value in &self.entity_names {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        for value in &self.entity_values {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.project.is_empty() {
            os.write_string(1, &self.project)?;
        }
        for v in &self.entity_names {
            os.write_string(2, &v)?;
        };
        for v in &self.entity_values {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RedisKeyV2 {
        RedisKeyV2::new()
    }

    fn clear(&mut self) {
        self.project.clear();
        self.entity_names.clear();
        self.entity_values.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RedisKeyV2 {
        static instance: RedisKeyV2 = RedisKeyV2 {
            project: ::std::string::String::new(),
            entity_names: ::std::vec::Vec::new(),
            entity_values: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RedisKeyV2 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RedisKeyV2").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RedisKeyV2 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RedisKeyV2 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19feast/storage/Redis.proto\x12\rfeast.storage\x1a\x17feast/types/Va\
    lue.proto\"\x82\x01\n\nRedisKeyV2\x12\x18\n\x07project\x18\x01\x20\x01(\
    \tR\x07project\x12!\n\x0centity_names\x18\x02\x20\x03(\tR\x0bentityNames\
    \x127\n\rentity_values\x18\x03\x20\x03(\x0b2\x12.feast.types.ValueR\x0ce\
    ntityValuesBU\n\x13feast.proto.storageB\nRedisProtoZ2github.com/feast-de\
    v/feast/go/protos/feast/storageJ\xfd\x06\n\x06\x12\x04\x10\0\x20\x01\n\
    \xc5\x04\n\x01\x0c\x12\x03\x10\0\x122\xba\x04\n\x20Copyright\x202019\x20\
    The\x20Feast\x20Authors\n\n\x20Licensed\x20under\x20the\x20Apache\x20Lic\
    ense,\x20Version\x202.0\x20(the\x20\"License\");\n\x20you\x20may\x20not\
    \x20use\x20this\x20file\x20except\x20in\x20compliance\x20with\x20the\x20\
    License.\n\x20You\x20may\x20obtain\x20a\x20copy\x20of\x20the\x20License\
    \x20at\n\n\x20\x20\x20\x20\x20https://www.apache.org/licenses/LICENSE-2.\
    0\n\n\x20Unless\x20required\x20by\x20applicable\x20law\x20or\x20agreed\
    \x20to\x20in\x20writing,\x20software\n\x20distributed\x20under\x20the\
    \x20License\x20is\x20distributed\x20on\x20an\x20\"AS\x20IS\"\x20BASIS,\n\
    \x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\x20ANY\x20KIND,\x20e\
    ither\x20express\x20or\x20implied.\n\x20See\x20the\x20License\x20for\x20\
    the\x20specific\x20language\x20governing\x20permissions\x20and\n\x20limi\
    tations\x20under\x20the\x20License.\n\n\t\n\x02\x03\0\x12\x03\x12\0!\n\
    \x08\n\x01\x02\x12\x03\x14\0\x16\n\x08\n\x01\x08\x12\x03\x16\0+\n\t\n\
    \x02\x08\x08\x12\x03\x16\0+\n\x08\n\x01\x08\x12\x03\x17\0,\n\t\n\x02\x08\
    \x01\x12\x03\x17\0,\n\x08\n\x01\x08\x12\x03\x18\0I\n\t\n\x02\x08\x0b\x12\
    \x03\x18\0I\n\n\n\x02\x04\0\x12\x04\x1a\0\x20\x01\n\n\n\x03\x04\0\x01\
    \x12\x03\x1a\x08\x12\n\x0b\n\x04\x04\0\x02\0\x12\x03\x1b\x02\x15\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x1b\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x1b\t\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x1b\x13\x14\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x1d\x02#\n\x0c\n\x05\x04\0\x02\x01\x04\x12\
    \x03\x1d\x02\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x1d\x0b\x11\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x1d\x12\x1e\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x1d!\"\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x1f\x02/\n\x0c\n\x05\
    \x04\0\x02\x02\x04\x12\x03\x1f\x02\n\n\x0c\n\x05\x04\0\x02\x02\x06\x12\
    \x03\x1f\x0b\x1c\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x1f\x1d*\n\x0c\n\
    \x05\x04\0\x02\x02\x03\x12\x03\x1f-.b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::Value::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RedisKeyV2::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
